### ISSUE TITLE
If you ctrl-c multiple times without pasting objects keep getting created even if you don't end up pasting them

### ISSUE THREAD

**Issue by Hazem-Gamall** [Charged-Entertainment/Charged-Learning#12]
## Expected Behavior

Only components that are present in the game should be created.
(DetachChildren should be called at the beginning of copy)

## Current Behavior

A lot of unused inactive objects get created.
## Possible Solution

We already have a list of the objects to be copied, so we will just delegate the Instantiation to the Paste method.
## Steps to Reproduce

1. Select some components.
2. Spam ctrl-c
3. Watch the editor get filled with inactive components.

**Comment by nourgaser** [comment]
I added a 'Clear()' that gets called on copy. But I'm not sure on the whole delegating instantiation to paste, I think the object should be copied in its current state, since it could be pasted later (or even in a different scene) when paste is called and the original object has changed or no longer alive. @Hazem-Gamall
