### ISSUE TITLE
The terminal in its smallest status looks weird . .

### ISSUE THREAD

**Issue by 1Rooky** [Charged-Entertainment/Charged-Learning#27]
The shrink icon not showing +  the terminal should be at least all rounded corners in its smallest mood

![image](https://user-images.githubusercontent.com/76395068/218247585-0781f996-c5e2-4342-9fa6-4b05cbbb0bdd.png)

**Comment by Hazem-Gamall** [comment]
this is how it looks now. 
But further comment is required from the design team @1Rooky 
Also design a shrink button to be added, or maybe the one button we have should toggle between all 3 states?

That's how it currently looks
![Screenshot from 2023-02-12 16-25-56](https://user-images.githubusercontent.com/68470388/218316884-b0d2fefc-7f84-4c5f-82ee-1e7b3a5c8800.png)

**Comment by nourgaser** [comment]
We should create a button under the devices button for the terminal. Instead of minimizing it, we should just give the player to close it completely.

- Add a 'Terminal' icon button to spawn the terminal (it'll be spawned by default).
     - [ ] Design the button icon. It should be the same size as the book icon, the devices icons, and should be right underneath them. @1Rooky 
     - [ ] Add the button to the game. @nourgaser 
- [ ] Add a close button with an 'X' icon to the terminal to close it. @nourgaser 
- [ ] The icon button should be clickable only when the terminal is closed, otherwise disabled, and re-enabled when it's closed.  @nourgaser

**Comment by nourgaser** [comment]
Closed with 9de5e83.
